### PR TITLE
Add recursive symlink scanning.

### PR DESCRIPTION
**Pull request by davidlehn**
Fixes https://github.com/digitalbazaar/bedrock-webpack/issues/23.

@gannan08 Please test. What's the best test case setup for your original request? I was having success with what I thought was a proper test even without this patch.

### CODE REVIEW

**Comment by gannan08** [comment]
> Fixes #23.
> 
> @gannan08 Please test. What's the best test case setup for your original request? I was having success with what I thought was a proper test even without this patch.

The best test case is to run a Product.

That product should have the structure of `node_modules/moduleA/node_modules/moduleB/` where `moduleA` is a symlinked packaged on a developer's machine and `moduleB` is also a symlinked package on a a developer's machine.

The desired behavior is to edit files in `moduleB` and have webpack pick up the file change and trigger a rebuild.

**Comment by davidlehn** [comment]
Ok.  I think I was testing it the wrong way.  Sadly this doesn't handle the double symlink HMR updates.  It does find and list the symlinks though.  It's a partial solution if someone wants to debug it further.

**Comment by mattcollier** [comment]
@davidlehn does this PR address an existing concern?

**Comment by davidlehn** [comment]
@mattcollier It is rarely an "existing concern".  But if it is at some point, this PR is a head start on a fix.

**Review by dlongley — APPROVED** [review]
I understand this doesn't fully work -- but maybe helps a little or gets us on a "headstart" to a full fix? If so, approving.

**Comment by davidlehn** [comment]
- It seems time changed how the previous solution should work.
- Symlinks seem to work as expected with the current config.  Changes to symlinked code were triggering a HMR rebuild, but the hash calculation wasn't changing.
- Using the `snapshot.unmanagedPaths` API seems to cause paths to be recognized as something that can change and a cache isn't used during hash calculation.
- End result on my tests seems to be that HMR works as one would like for symlinked deps at top level, scoped, or sub-deps.
- By default only the top level and scopes are scanned for symlinks for performance reasons.  `--webpack-hmr-paths all` will scan everything, but that assumed to not be the common case.
- A related HMR issue is directly editing installed source.  You may have to use the `--webpack-hmr-path fullpath` option on that package to handle the similar cache issues that effected symlinks.
- Please test.

**Review by jameseaster — APPROVED** [review]
Worked awesomely in my local environment. Thanks @davidlehn!

**Review by dlongley — APPROVED** [review]
Happy for this to be merged and released.

**Pull request merged**
